#!/usr/bin/env python3
"""Write locked Chinese translations onto externally cleaned page images.

This module deliberately contains no English-text removal, masking, redaction,
or inpainting code.  It consumes ``*.cleaned.png`` files produced beforehand by
``erase_english_from_deepseek.py``, a locked final-translation snapshot, and the
coordinate plan generated by ``codex_book_finalize.py``.
"""

from __future__ import annotations

import argparse
import copy
import datetime as dt
import json
import math
import pathlib
import re
import sys
from typing import Any

import codex_book_review as book_review
import codex_page_review as page_review


DEFAULT_RULES: dict[str, Any] = {
    "font_sizes": {
        "dialogue": 11.0,
        "question": 11.0,
        "instruction": 10.0,
        "explanation": 10.0,
        "definition": 10.0,
        "heading": 14.0,
        "contents": 10.0,
        "caption": 10.0,
        "footnote": 9.0,
        "other": 10.0,
    },
    "minimum_font_size": 7.0,
    "font_size_step": 0.5,
    "line_spacing": 1.25,
    "placement_padding_normalized": [4.0, 0.0, 4.0, 0.0],
    "page_margin_points": 6.0,
    "minimum_text_width_points": 72.0,
    "maximum_width_expansion": 1.15,
    "minimum_write_match_coverage": 0.65,
    "ambiguous_mapping_minimum_coverage": 0.90,
    "light_text_color": "#111111",
    "dark_text_color": "#FFFFFF",
    "dark_background_luminance": 115.0,
    "alignment_by_type": {
        "dialogue": "center",
        "question": "center",
        "instruction": "left",
        "explanation": "left",
        "definition": "left",
        "heading": "center",
        "contents": "left",
        "caption": "center",
        "footnote": "left",
        "other": "center",
    },
}


class PdfWriterError(RuntimeError):
    """Expected input, layout, font, or PDF validation failure."""


def require_dependencies() -> tuple[Any, Any, Any]:
    try:
        import pymupdf  # type: ignore
        from PIL import Image, ImageStat  # type: ignore
    except ImportError as error:
        raise PdfWriterError(
            "PDF writing requires PyMuPDF and Pillow in the active Python environment"
        ) from error
    return pymupdf, Image, ImageStat


def read_json(path: pathlib.Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except OSError as error:
        raise PdfWriterError(f"Cannot read {path}: {error}") from error
    except json.JSONDecodeError as error:
        raise PdfWriterError(f"Invalid JSON in {path}: {error}") from error


def atomic_write_json(path: pathlib.Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    temporary.replace(path)


def merge_rules(raw: dict[str, Any] | None) -> dict[str, Any]:
    rules = copy.deepcopy(DEFAULT_RULES)
    if raw is None:
        return rules
    if not isinstance(raw, dict):
        raise PdfWriterError("pdf_translation_writer.rules must be an object")
    unknown = sorted(set(raw) - set(DEFAULT_RULES))
    if unknown:
        raise PdfWriterError("Unknown writer rules: " + ", ".join(unknown))
    for key, value in raw.items():
        if isinstance(rules.get(key), dict) and isinstance(value, dict):
            rules[key].update(value)
        else:
            rules[key] = value
    if float(rules["minimum_font_size"]) <= 0:
        raise PdfWriterError("minimum_font_size must be positive")
    if float(rules["font_size_step"]) <= 0:
        raise PdfWriterError("font_size_step must be positive")
    if float(rules["line_spacing"]) < 1.0:
        raise PdfWriterError("line_spacing must be at least 1.0")
    for field in (
        "minimum_write_match_coverage",
        "ambiguous_mapping_minimum_coverage",
    ):
        if not 0 <= float(rules[field]) <= 1:
            raise PdfWriterError(f"{field} must be between 0 and 1")
    return rules


def load_layout_overrides(path: pathlib.Path | None) -> dict[tuple[int, str], dict[str, Any]]:
    if path is None:
        return {}
    payload = read_json(path)
    if not isinstance(payload, dict) or payload.get("schema_version") != 1:
        raise PdfWriterError("Unsupported layout override schema")
    raw_regions = payload.get("regions")
    if not isinstance(raw_regions, list):
        raise PdfWriterError("Layout override regions must be an array")
    result: dict[tuple[int, str], dict[str, Any]] = {}
    for raw in raw_regions:
        if not isinstance(raw, dict):
            raise PdfWriterError("Layout override must be an object")
        coordinate = (int(raw["page"]), str(raw["id"]))
        if coordinate in result:
            raise PdfWriterError(
                f"Duplicate layout override: p{coordinate[0]}-{coordinate[1]}"
            )
        allowed = {
            "page",
            "id",
            "skip",
            "force_write",
            "placement_box",
            "offset_x",
            "offset_y",
            "font_size",
            "text_color",
            "alignment",
            "vertical_alignment",
        }
        unknown = sorted(set(raw) - allowed)
        if unknown:
            raise PdfWriterError(
                f"Unknown layout override fields for p{coordinate[0]}-{coordinate[1]}: "
                + ", ".join(unknown)
            )
        result[coordinate] = dict(raw)
    return result


def validate_snapshot(
    snapshot: dict[str, Any], *, source_pdf: pathlib.Path, snapshot_path: pathlib.Path
) -> dict[tuple[int, str], dict[str, Any]]:
    if snapshot.get("schema_version") != 1 or snapshot.get("status") != "locked_final_translation":
        raise PdfWriterError("Final translation snapshot is not locked schema version 1")
    if pathlib.Path(str(snapshot.get("source_pdf", ""))).resolve() != source_pdf:
        raise PdfWriterError("Final translation snapshot belongs to a different PDF")
    inputs = snapshot.get("inputs")
    if not isinstance(inputs, dict):
        raise PdfWriterError("Final translation snapshot has no input hashes")
    adjudication_path = pathlib.Path(str(inputs.get("adjudication_file", "")))
    if not adjudication_path.is_file():
        raise PdfWriterError("Snapshot adjudication file is missing")
    if page_review.sha256_file(adjudication_path) != inputs.get("adjudication_sha256"):
        raise PdfWriterError("Snapshot adjudication file changed after locking")
    adjudication = read_json(adjudication_path)
    if not isinstance(adjudication, dict):
        raise PdfWriterError("Snapshot adjudication root must be an object")
    if adjudication.get("source_pdf_sha256") != page_review.sha256_file(source_pdf):
        raise PdfWriterError("Source PDF changed after finalization")
    regions = snapshot.get("regions")
    if not isinstance(regions, list) or len(regions) != snapshot.get("region_count"):
        raise PdfWriterError("Snapshot region count is inconsistent")
    result: dict[tuple[int, str], dict[str, Any]] = {}
    for raw in regions:
        if not isinstance(raw, dict):
            raise PdfWriterError("Snapshot region must be an object")
        coordinate = (int(raw["page"]), str(raw["id"]))
        if coordinate in result or raw.get("locked") is not True:
            raise PdfWriterError(
                f"Snapshot contains duplicate or unlocked region p{coordinate[0]}-{coordinate[1]}"
            )
        if not str(raw.get("final_translation", "")).strip():
            raise PdfWriterError(
                f"Snapshot contains empty translation p{coordinate[0]}-{coordinate[1]}"
            )
        result[coordinate] = raw
    return result


def validate_plan(
    plan: dict[str, Any],
    snapshot_regions: dict[tuple[int, str], dict[str, Any]],
) -> dict[tuple[int, str], dict[str, Any]]:
    if plan.get("schema_version") != 1:
        raise PdfWriterError("Unsupported coordinate plan schema")
    mappings = plan.get("mappings")
    if not isinstance(mappings, list):
        raise PdfWriterError("Coordinate plan mappings must be an array")
    result: dict[tuple[int, str], dict[str, Any]] = {}
    for mapping in mappings:
        if not isinstance(mapping, dict):
            raise PdfWriterError("Coordinate mapping must be an object")
        coordinate = (int(mapping["page"]), str(mapping["id"]))
        if coordinate in result or coordinate not in snapshot_regions:
            raise PdfWriterError(
                f"Coordinate plan has unknown or duplicate region p{coordinate[0]}-{coordinate[1]}"
            )
        if mapping.get("final_translation") != snapshot_regions[coordinate]["final_translation"]:
            raise PdfWriterError(
                f"Coordinate plan translation differs from snapshot p{coordinate[0]}-{coordinate[1]}"
            )
        result[coordinate] = mapping
    missing = sorted(set(snapshot_regions) - set(result))
    if missing:
        joined = ", ".join(f"p{page}-{region_id}" for page, region_id in missing[:20])
        raise PdfWriterError("Coordinate plan is incomplete: " + joined)
    if plan.get("layout_item_ownership_conflict_count"):
        raise PdfWriterError("Coordinate plan contains layout ownership conflicts")
    return result


def discover_cleaned_pages(
    directory: pathlib.Path, pages: list[int]
) -> tuple[dict[int, pathlib.Path], list[int]]:
    found: dict[int, pathlib.Path] = {}
    missing: list[int] = []
    for page in pages:
        matches = list(directory.rglob(f"page-{page:04d}.cleaned.png"))
        if len(matches) > 1:
            raise PdfWriterError(f"Multiple cleaned images found for PDF page {page}")
        if not matches:
            missing.append(page)
        else:
            found[page] = matches[0].resolve()
    return found, missing


def resolve_font(configured: pathlib.Path | None) -> pathlib.Path:
    candidates = [configured] if configured is not None else []
    candidates.extend(
        [
            pathlib.Path("C:/Windows/Fonts/simhei.ttf"),
            pathlib.Path("C:/Windows/Fonts/Deng.ttf"),
            pathlib.Path("/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"),
            pathlib.Path("/System/Library/Fonts/PingFang.ttc"),
        ]
    )
    for candidate in candidates:
        if candidate is not None and candidate.is_file():
            return candidate.resolve()
    raise PdfWriterError("A Chinese TrueType/OpenType font file was not found")


def hex_color(value: str) -> tuple[float, float, float]:
    match = re.fullmatch(r"#([0-9a-fA-F]{6})", str(value).strip())
    if not match:
        raise PdfWriterError(f"Invalid RGB color: {value}")
    raw = match.group(1)
    return tuple(int(raw[index : index + 2], 16) / 255 for index in (0, 2, 4))


def normalized_rect(pymupdf: Any, box: list[float], page_rect: Any) -> Any:
    if len(box) != 4:
        raise PdfWriterError("Normalized placement_box must contain four values")
    x0, y0, x1, y1 = [float(value) for value in box]
    if x1 <= x0 or y1 <= y0:
        raise PdfWriterError(f"Invalid normalized placement box: {box}")
    return pymupdf.Rect(
        page_rect.x0 + page_rect.width * x0 / 1000,
        page_rect.y0 + page_rect.height * y0 / 1000,
        page_rect.x0 + page_rect.width * x1 / 1000,
        page_rect.y0 + page_rect.height * y1 / 1000,
    )


def padded_placement_box(box: list[float], padding: list[float]) -> list[float]:
    if len(padding) != 4:
        raise PdfWriterError("placement_padding_normalized must contain four values")
    return [
        max(0.0, float(box[0]) - float(padding[0])),
        max(0.0, float(box[1]) - float(padding[1])),
        min(1000.0, float(box[2]) + float(padding[2])),
        min(1000.0, float(box[3]) + float(padding[3])),
    ]


def wrap_text(font: Any, text: str, font_size: float, width: float) -> list[str]:
    lines: list[str] = []
    current = ""
    for character in text:
        if character == "\n":
            lines.append(current)
            current = ""
            continue
        candidate = current + character
        if current and font.text_length(candidate, fontsize=font_size) > width:
            lines.append(current)
            current = character
        else:
            current = candidate
    if current or not lines:
        lines.append(current)
    return lines


def fit_text(
    font: Any,
    text: str,
    rect: Any,
    *,
    default_size: float,
    rules: dict[str, Any],
) -> tuple[float, list[str], float]:
    size = default_size
    minimum = float(rules["minimum_font_size"])
    step = float(rules["font_size_step"])
    while True:
        lines = wrap_text(font, text, size, max(1.0, rect.width))
        height = len(lines) * size * float(rules["line_spacing"])
        if height <= rect.height or size <= minimum:
            return max(size, minimum), lines, height
        size = max(minimum, size - step)


def sample_background(
    Image: Any,
    ImageStat: Any,
    image_path: pathlib.Path,
    normalized_box: list[float],
) -> tuple[float, float, float]:
    with Image.open(image_path) as opened:
        image = opened.convert("RGB")
        width, height = image.size
        x0, y0, x1, y1 = normalized_box
        crop_box = (
            max(0, min(width - 1, round(width * float(x0) / 1000))),
            max(0, min(height - 1, round(height * float(y0) / 1000))),
            max(1, min(width, round(width * float(x1) / 1000))),
            max(1, min(height, round(height * float(y1) / 1000))),
        )
        if crop_box[2] <= crop_box[0] or crop_box[3] <= crop_box[1]:
            return (1.0, 1.0, 1.0)
        median = ImageStat.Stat(image.crop(crop_box)).median
        return tuple(float(value) / 255 for value in median[:3])


def luminance(color: tuple[float, float, float]) -> float:
    return (color[0] * 0.2126 + color[1] * 0.7152 + color[2] * 0.0722) * 255


def skip_reason(mapping: dict[str, Any], override: dict[str, Any], rules: dict[str, Any]) -> str | None:
    if override.get("skip"):
        return "skipped_by_override"
    if not mapping.get("placement_box"):
        return "unmatched_skipped"
    if override.get("force_write"):
        return None
    coverage = float(mapping.get("match_coverage", 0.0))
    if coverage < float(rules["minimum_write_match_coverage"]):
        return "skipped_low_confidence"
    if (
        "ambiguous_layout_candidates" in mapping.get("warnings", [])
        and coverage < float(rules["ambiguous_mapping_minimum_coverage"])
    ):
        return "skipped_ambiguous_mapping"
    return None


def write_pdf(
    *,
    source_pdf: pathlib.Path,
    snapshot: dict[str, Any],
    plan: dict[str, Any],
    cleaned_pages: dict[int, pathlib.Path],
    font_file: pathlib.Path,
    output_pdf: pathlib.Path,
    rules: dict[str, Any],
    overrides: dict[tuple[int, str], dict[str, Any]],
) -> dict[str, Any]:
    pymupdf, Image, ImageStat = require_dependencies()
    snapshot_pages = sorted(int(page) for page in snapshot["pages"])
    mappings_by_page: dict[int, list[dict[str, Any]]] = {}
    valid_coordinates: set[tuple[int, str]] = set()
    for mapping in plan["mappings"]:
        page = int(mapping["page"])
        mappings_by_page.setdefault(page, []).append(mapping)
        valid_coordinates.add((page, str(mapping["id"])))
    unknown_overrides = sorted(set(overrides) - valid_coordinates)
    if unknown_overrides:
        raise PdfWriterError(
            "Layout overrides reference unknown regions: "
            + ", ".join(f"p{p}-{r}" for p, r in unknown_overrides)
        )
    source = pymupdf.open(source_pdf)
    source_page_count = source.page_count
    output = pymupdf.open()
    regions: list[dict[str, Any]] = []
    cleaned_hashes: dict[str, str] = {}
    try:
        font = pymupdf.Font(fontfile=str(font_file))
        for page_number in range(1, source.page_count + 1):
            source_page = source[page_number - 1]
            target = output.new_page(
                width=source_page.rect.width, height=source_page.rect.height
            )
            if page_number in cleaned_pages:
                image_path = cleaned_pages[page_number]
                target.insert_image(
                    target.rect,
                    filename=str(image_path),
                    keep_proportion=False,
                    overlay=True,
                )
                cleaned_hashes[image_path.name] = page_review.sha256_file(image_path)
            else:
                target.show_pdf_page(target.rect, source, page_number - 1)
            if page_number not in snapshot_pages:
                continue
            target.insert_font(fontname="zhfont", fontfile=str(font_file))
            for raw_mapping in mappings_by_page.get(page_number, []):
                mapping = copy.deepcopy(raw_mapping)
                coordinate = (page_number, str(mapping["id"]))
                override = overrides.get(coordinate, {})
                reason = skip_reason(mapping, override, rules)
                if reason:
                    regions.append(
                        {
                            "page": page_number,
                            "id": mapping["id"],
                            "status": reason,
                            "warnings": mapping.get("warnings", []),
                        }
                    )
                    continue
                placement = [
                    float(value)
                    for value in override.get(
                        "placement_box", mapping["placement_box"]
                    )
                ]
                if override.get("offset_x"):
                    placement[0] += float(override["offset_x"])
                    placement[2] += float(override["offset_x"])
                if override.get("offset_y"):
                    placement[1] += float(override["offset_y"])
                    placement[3] += float(override["offset_y"])
                placement = padded_placement_box(
                    placement, rules["placement_padding_normalized"]
                )
                rect = normalized_rect(pymupdf, placement, target.rect)
                margin = float(rules["page_margin_points"])
                rect &= pymupdf.Rect(
                    margin,
                    margin,
                    target.rect.width - margin,
                    target.rect.height - margin,
                )
                background = sample_background(
                    Image, ImageStat, cleaned_pages[page_number], placement
                )
                text_color = (
                    hex_color(str(override["text_color"]))
                    if override.get("text_color")
                    else hex_color(
                        rules["dark_text_color"]
                        if luminance(background)
                        < float(rules["dark_background_luminance"])
                        else rules["light_text_color"]
                    )
                )
                region_type = str(mapping.get("type", "other"))
                default_size = float(
                    override.get(
                        "font_size",
                        rules["font_sizes"].get(
                            region_type, rules["font_sizes"]["other"]
                        ),
                    )
                )
                font_size, lines, block_height = fit_text(
                    font,
                    str(mapping["final_translation"]),
                    rect,
                    default_size=default_size,
                    rules=rules,
                )
                alignment = str(
                    override.get(
                        "alignment",
                        rules["alignment_by_type"].get(region_type, "left"),
                    )
                )
                if alignment not in {"left", "center", "right"}:
                    raise PdfWriterError(
                        f"Invalid alignment p{page_number}-{mapping['id']}"
                    )
                vertical = str(
                    override.get(
                        "vertical_alignment",
                        "center"
                        if region_type
                        in {"dialogue", "question", "caption", "heading", "other"}
                        else "top",
                    )
                )
                if vertical not in {"top", "center"}:
                    raise PdfWriterError(
                        f"Invalid vertical alignment p{page_number}-{mapping['id']}"
                    )
                line_height = font_size * float(rules["line_spacing"])
                y = rect.y0 + font_size
                if vertical == "center":
                    y += max(0.0, (rect.height - block_height) / 2)
                for line in lines:
                    width = font.text_length(line, fontsize=font_size)
                    x = rect.x0
                    if alignment == "center":
                        x += max(0.0, (rect.width - width) / 2)
                    elif alignment == "right":
                        x = rect.x1 - width
                    target.insert_text(
                        (x, y),
                        line,
                        fontname="zhfont",
                        fontsize=font_size,
                        color=text_color,
                        overlay=True,
                    )
                    y += line_height
                regions.append(
                    {
                        "page": page_number,
                        "id": mapping["id"],
                        "status": "written",
                        "font_size": font_size,
                        "line_count": len(lines),
                        "alignment": alignment,
                        "vertical_alignment": vertical,
                        "text_rect": [
                            round(rect.x0, 3),
                            round(rect.y0, 3),
                            round(rect.x1, 3),
                            round(rect.y1, 3),
                        ],
                        "warnings": mapping.get("warnings", []),
                    }
                )
        output_pdf.parent.mkdir(parents=True, exist_ok=True)
        temporary = output_pdf.with_suffix(output_pdf.suffix + ".tmp")
        output.save(temporary, garbage=3, deflate=True)
        output.close()
        temporary.replace(output_pdf)
    finally:
        source.close()
        if not output.is_closed:
            output.close()
    status_counts: dict[str, int] = {}
    for region in regions:
        status = str(region["status"])
        status_counts[status] = status_counts.get(status, 0) + 1
    written = [region for region in regions if region.get("status") == "written"]
    severe_overlaps: list[dict[str, Any]] = []
    for index, first in enumerate(written):
        first_rect = first["text_rect"]
        for second in written[index + 1 :]:
            if first["page"] != second["page"]:
                continue
            second_rect = second["text_rect"]
            width = max(
                0.0,
                min(first_rect[2], second_rect[2])
                - max(first_rect[0], second_rect[0]),
            )
            height = max(
                0.0,
                min(first_rect[3], second_rect[3])
                - max(first_rect[1], second_rect[1]),
            )
            intersection = width * height
            first_area = max(
                1.0,
                (first_rect[2] - first_rect[0])
                * (first_rect[3] - first_rect[1]),
            )
            second_area = max(
                1.0,
                (second_rect[2] - second_rect[0])
                * (second_rect[3] - second_rect[1]),
            )
            ratio = intersection / min(first_area, second_area)
            if ratio >= 0.35:
                severe_overlaps.append(
                    {
                        "page": first["page"],
                        "first_id": first["id"],
                        "second_id": second["id"],
                        "overlap_ratio": round(ratio, 4),
                    }
                )
    return {
        "schema_version": 1,
        "edition": "chinese",
        "output_pdf": str(output_pdf),
        "source_page_count": source_page_count,
        "translated_page_count": len(snapshot_pages),
        "region_count": len(regions),
        "status_counts": dict(sorted(status_counts.items())),
        "severe_text_overlap_count": len(severe_overlaps),
        "severe_text_overlaps": severe_overlaps,
        "cleaned_pages": {
            "producer": "erase_english_from_deepseek.py",
            "writer_performed_erasure": False,
            "files": dict(sorted(cleaned_hashes.items())),
        },
        "regions": regions,
    }


def program_check(
    *,
    source_pdf: pathlib.Path,
    output_pdf: pathlib.Path,
    snapshot: dict[str, Any],
    plan: dict[str, Any],
    export: dict[str, Any],
) -> dict[str, Any]:
    pymupdf, _Image, _ImageStat = require_dependencies()
    checks: list[dict[str, Any]] = []

    def add(name: str, passed: bool, detail: Any) -> None:
        checks.append({"name": name, "passed": bool(passed), "detail": detail})

    add("output_exists", output_pdf.is_file(), str(output_pdf))
    add(
        "output_nonempty",
        output_pdf.is_file() and output_pdf.stat().st_size > 0,
        output_pdf.stat().st_size if output_pdf.is_file() else 0,
    )
    if output_pdf.is_file():
        source = pymupdf.open(source_pdf)
        output = pymupdf.open(output_pdf)
        try:
            add("pdf_reopens", not output.is_closed, "opened with PyMuPDF")
            add("full_page_count", output.page_count == source.page_count, output.page_count)
            size_mismatches = [
                page_number
                for page_number in range(min(source.page_count, output.page_count))
                if (
                    round(source[page_number].rect.width, 3),
                    round(source[page_number].rect.height, 3),
                )
                != (
                    round(output[page_number].rect.width, 3),
                    round(output[page_number].rect.height, 3),
                )
            ]
            add("page_sizes", not size_mismatches, size_mismatches)
            add(
                "all_pages_nonempty",
                all(page.rect.width > 0 and page.rect.height > 0 for page in output),
                output.page_count,
            )
        finally:
            source.close()
            output.close()
    add(
        "snapshot_locked",
        all(region.get("locked") is True for region in snapshot.get("regions", [])),
        snapshot.get("region_count"),
    )
    add(
        "plan_coordinate_ownership_unique",
        plan.get("layout_item_ownership_conflict_count") == 0,
        plan.get("layout_item_ownership_conflicts", []),
    )
    add(
        "all_mappings_accounted_for",
        export.get("region_count") == len(plan.get("mappings", [])),
        {
            "export_regions": export.get("region_count"),
            "plan_mappings": len(plan.get("mappings", [])),
        },
    )
    add(
        "all_translated_pages_use_cleaned_images",
        len(export.get("cleaned_pages", {}).get("files", {}))
        == int(snapshot.get("page_count", 0)),
        len(export.get("cleaned_pages", {}).get("files", {})),
    )
    add(
        "severe_text_overlaps",
        export.get("severe_text_overlap_count") == 0,
        export.get("severe_text_overlaps", []),
    )
    add(
        "writer_did_not_erase",
        export.get("cleaned_pages", {}).get("writer_performed_erasure") is False,
        export.get("cleaned_pages", {}).get("producer"),
    )
    return {
        "schema_version": 1,
        "status": "program_checked" if all(check["passed"] for check in checks) else "failed",
        "visual_review": "not_performed_human_required",
        "checks": checks,
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().with_name("ocr_config.json"),
    )
    parser.add_argument("--pdf", type=pathlib.Path)
    parser.add_argument("--snapshot", type=pathlib.Path)
    parser.add_argument("--plan", type=pathlib.Path)
    parser.add_argument("--cleaned-pages-dir", type=pathlib.Path)
    parser.add_argument("--font-file", type=pathlib.Path)
    parser.add_argument("--layout-overrides", type=pathlib.Path)
    parser.add_argument("--output", type=pathlib.Path)
    parser.add_argument("--report", type=pathlib.Path)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        config_path = args.config.expanduser().resolve()
        config = book_review.read_json(config_path, jsonc=True)
        if not isinstance(config, dict):
            raise PdfWriterError("Config root must be an object")
        base_output = book_review.resolve_config_path(
            config.get("output"), config_path=config_path
        )
        if base_output is None:
            raise PdfWriterError("Config output directory is required")
        backfill = config.get("pdf_backfill", {})
        writer_config = config.get("pdf_translation_writer", {})
        if not isinstance(backfill, dict) or not isinstance(writer_config, dict):
            raise PdfWriterError("PDF writer/backfill configuration must be an object")
        allowed_writer_fields = {
            "cleaned_pages_dir",
            "output_filename",
            "report_filename",
            "font_file",
            "rules",
        }
        unknown_writer_fields = sorted(set(writer_config) - allowed_writer_fields)
        if unknown_writer_fields:
            raise PdfWriterError(
                "Unknown pdf_translation_writer fields: "
                + ", ".join(unknown_writer_fields)
            )
        source_pdf = (
            args.pdf.expanduser().resolve()
            if args.pdf
            else book_review.resolve_config_path(config.get("pdf"), config_path=config_path)
        )
        if source_pdf is None or not source_pdf.is_file():
            raise PdfWriterError(f"Source PDF not found: {source_pdf}")

        def output_path(value: Any, default: str) -> pathlib.Path:
            path = pathlib.Path(str(value or default)).expanduser()
            if not path.is_absolute():
                path = base_output / path
            return path.resolve()

        snapshot_path = (
            args.snapshot.expanduser().resolve()
            if args.snapshot
            else output_path(
                backfill.get("final_translation_filename"),
                "chapter_translation_final.json",
            )
        )
        plan_path = (
            args.plan.expanduser().resolve()
            if args.plan
            else output_path(backfill.get("plan_filename"), "pdf_backfill_plan.json")
        )
        output_pdf = (
            args.output.expanduser().resolve()
            if args.output
            else output_path(
                writer_config.get("output_filename", backfill.get("output_filename")),
                "book-zh-review.pdf",
            )
        )
        report_path = (
            args.report.expanduser().resolve()
            if args.report
            else output_path(
                writer_config.get("report_filename", backfill.get("report_filename")),
                "pdf_translation_writer_report.json",
            )
        )
        cleaned_dir = (
            args.cleaned_pages_dir.expanduser().resolve()
            if args.cleaned_pages_dir
            else book_review.resolve_config_path(
                writer_config.get("cleaned_pages_dir"), config_path=config_path
            )
        )
        if cleaned_dir is None:
            raise PdfWriterError(
                "--cleaned-pages-dir or pdf_translation_writer.cleaned_pages_dir is required"
            )
        if not cleaned_dir.is_dir():
            raise PdfWriterError(f"Cleaned page directory not found: {cleaned_dir}")
        configured_font_value = args.font_file or writer_config.get("font_file") or backfill.get("font_file")
        configured_font = None
        if configured_font_value:
            configured_font = pathlib.Path(configured_font_value).expanduser()
            if not configured_font.is_absolute():
                configured_font = config_path.parent / configured_font
        font_file = resolve_font(configured_font)
        snapshot = read_json(snapshot_path)
        plan = read_json(plan_path)
        if not isinstance(snapshot, dict) or not isinstance(plan, dict):
            raise PdfWriterError("Snapshot and coordinate plan roots must be objects")
        snapshot_regions = validate_snapshot(
            snapshot, source_pdf=source_pdf, snapshot_path=snapshot_path
        )
        validate_plan(plan, snapshot_regions)
        pages = sorted(int(page) for page in snapshot.get("pages", []))
        cleaned_pages, missing = discover_cleaned_pages(cleaned_dir, pages)
        if args.dry_run:
            print(
                json.dumps(
                    {
                        "source_pdf": str(source_pdf),
                        "source_pdf_sha256": page_review.sha256_file(source_pdf),
                        "snapshot": str(snapshot_path),
                        "snapshot_sha256": page_review.sha256_file(snapshot_path),
                        "plan": str(plan_path),
                        "plan_sha256": page_review.sha256_file(plan_path),
                        "translated_pages": len(pages),
                        "cleaned_pages_found": len(cleaned_pages),
                        "missing_cleaned_pages": missing,
                        "font_file": str(font_file),
                        "output": str(output_pdf),
                        "writer_performs_erasure": False,
                        "would_write": False,
                    },
                    ensure_ascii=False,
                )
            )
            return 0
        if missing:
            raise PdfWriterError(
                "Missing externally cleaned page images: "
                + ", ".join(str(page) for page in missing[:30])
                + ("..." if len(missing) > 30 else "")
            )
        for path in (output_pdf, report_path):
            if path.exists() and not args.force:
                raise PdfWriterError(f"Output exists: {path}; pass --force to replace it")
        rules = merge_rules(writer_config.get("rules"))
        override_path = (
            args.layout_overrides.expanduser().resolve()
            if args.layout_overrides
            else None
        )
        overrides = load_layout_overrides(override_path)
        export = write_pdf(
            source_pdf=source_pdf,
            snapshot=snapshot,
            plan=plan,
            cleaned_pages=cleaned_pages,
            font_file=font_file,
            output_pdf=output_pdf,
            rules=rules,
            overrides=overrides,
        )
        checked = program_check(
            source_pdf=source_pdf,
            output_pdf=output_pdf,
            snapshot=snapshot,
            plan=plan,
            export=export,
        )
        report = {
            "schema_version": 1,
            "status": checked["status"],
            "visual_review": "not_performed_human_required",
            "inputs": {
                "source_pdf": str(source_pdf),
                "source_pdf_sha256": page_review.sha256_file(source_pdf),
                "snapshot": str(snapshot_path),
                "snapshot_sha256": page_review.sha256_file(snapshot_path),
                "plan": str(plan_path),
                "plan_sha256": page_review.sha256_file(plan_path),
                "layout_overrides": str(override_path) if override_path else None,
                "layout_overrides_sha256": (
                    page_review.sha256_file(override_path) if override_path else None
                ),
            },
            "font_file": str(font_file),
            "export": export,
            "program_check": checked,
            "created_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        }
        atomic_write_json(report_path, report)
        print(
            json.dumps(
                {
                    "status": checked["status"],
                    "written": export["status_counts"].get("written", 0),
                    "output": str(output_pdf),
                    "report": str(report_path),
                    "visual_review": "human_required",
                },
                ensure_ascii=False,
            )
        )
        return 0 if checked["status"] == "program_checked" else 1
    except (PdfWriterError, book_review.BookReviewError, ValueError) as error:
        parser.error(str(error))
        return 2


if __name__ == "__main__":
    sys.exit(main())
